#!/bin/sh
#
# Starts TS-8820-4100 demo
#

DAEMON="TS-8820-4100 Demo"

umask 077

start() {
	printf 'Set up ADC: '
	/usr/bin/gpioset 3 26=0
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi

	printf 'Loading ZPU: '
	/usr/bin/tszpuctl -l /usr/bin/zpu/zpu_offload_demo.bin >/dev/null 2>&1
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi

	printf 'Starting %s: ' "$DAEMON"
	start-stop-daemon -S -q -m -p /var/run/zpu_demo_interface.pid -b --exec sh /usr/bin/zpu_demo_interface.sh
	echo "OK"
}
stop() {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -K -q -m -p /var/run/zpu_demo_interface.pid -b --exec sh /usr/bin/zpu_demo_interface.sh
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
